---
title: "BPM"
---


<a href="salary_bpm_col.html">BPM and salary</a>

<a href="clutch_3pt.html">Clutch 3-point shooting, 2014-2019</a>

<b>Team performance so far this season:</b>

```{r,echo=FALSE,warning=FALSE,message=FALSE}
library(tidyverse)
library(rvest)
library(janitor)
library(reactable)
library(htmltools)
tratings <- function(year, format){
  
  # Vector of column names 
  cols <- c("team", "wins", "losses", "win_pct", "mov", "orating", "drating",
            "netrating", "mov_adj", "orating_ajd", "drating_adj", "netrating_ajd")
  
  # Retrieving a single year
  if(length(year) == 1){
    return(paste0("https://www.basketball-reference.com/leagues/NBA_", 
                  year, "_ratings.html") %>% 
             read_html() %>% 
             html_nodes("#ratings") %>% 
             html_table() %>% 
             as.data.frame() %>% 
             row_to_names(1) %>% # first row is column names
             dplyr::select(-Rk, -Conf, -Div) %>% # useless columns
             magrittr::set_colnames(cols) %>% 
             mutate_all(as.character) %>% 
             mutate_at(.vars = vars(wins:netrating_ajd), 
                       as.numeric) %>% 
             mutate(orating_rel = orating - mean(orating),
                    drating_rel = drating - mean(drating)))
  }
  
  else if(length(year) > 1){
    out <- matrix(nrow = 30*length(year), ncol = 13)
    
    for(i in 1:length(year)){
      out[((i-1)*30+1):(i*30),] <- paste0("https://www.basketball-reference.com/leagues/NBA_", 
                                     year[i], "_ratings.html") %>% 
        read_html() %>% 
        html_nodes("#ratings") %>% 
        html_table() %>% 
        as.data.frame() %>% 
        row_to_names(1) %>% 
        dplyr::select(-Rk, -Conf, -Div) %>%
        magrittr::set_colnames(cols) %>% 
        mutate(year = year[i]) %>% 
        as.matrix()
    }
    
    if(format == "long"){
      # to df class and setting column names (with year added)
      return(as.data.frame(out) %>% 
               magrittr::set_colnames(c(cols, "year")) %>% 
               mutate_all(as.character) %>% 
               mutate_at(.vars = vars(wins:netrating_ajd), 
                         as.numeric) %>% 
               group_by(year) %>% 
               mutate(orating_rel = orating - mean(orating),
                      drating_rel = drating - mean(drating)))
    }
    
    if(format == "wide"){
      return(as.data.frame(out) %>% 
               magrittr::set_colnames(c(cols, "year")) %>% 
               mutate_all(as.character) %>%
               mutate_at(.vars = vars(wins:netrating_ajd), 
                         as.numeric) %>% 
               group_by(year) %>% 
               mutate(orating_rel = orating - mean(orating),
                      drating_rel = drating - mean(drating)) %>% 
               pivot_wider(names_from = "year", values_from = wins:netrating_ajd))
    }
  }
}

# Functions to handle cell colors copied from: https://glin.github.io/reactable/articles/womens-world-cup/womens-world-cup.html
make_color_pal <- function(colors, bias = 1) {
  get_color <- colorRamp(colors, bias = bias)
  function(x) rgb(get_color(x), maxColorValue = 255)
}

# Compared to website above, inverted the vector of colors to make it from red to green 
ratings_color <- make_color_pal(c("#44ab43", "#f8fcf8", "#ff2700"), bias = 1.3)

# Keeping original order here so that lower drtg results in greener color 
dratings_color <- make_color_pal(c("#ff2700", "#f8fcf8", "#44ab43"), bias = 1.3)

ratings_2021 <- tratings(2021) %>% 
  dplyr::select(team, wins, losses, orating_ajd, drating_adj, netrating_ajd)

reactable::reactable(
  ratings_2021,
  columns = list(
    orating_ajd = colDef(
      class = "cell number",
      cell = function(value){
        scaled <- 1 - (value - min(ratings_2021$orating_ajd)) / (max(ratings_2021$orating_ajd) - min(ratings_2021$orating_ajd))
        color <- ratings_color(scaled)
        div(class = "spi-rating", style = list(background = color), value)
      }
    ),
    drating_adj = colDef(
      class = "cell number",
      cell = function(value){
        scaled <- 1 - (value - min(ratings_2021$drating_adj)) / (max(ratings_2021$drating_adj) - min(ratings_2021$drating_adj))
        color <- dratings_color(scaled)
        div(class = "spi-rating", style = list(background = color), value)
      }
    )
  )
)
```


<b>Biggest year-over-year decline in rORTG:</b>

```{r,echo=FALSE,message=FALSE,warning=FALSE}

# Loading data
load("tratings.Rdata")

# Transforming data to get 10 largest declines in rORTG
ratings <- tratings_changes_2011_2021 %>% 
  arrange(orating_rel_change) %>% 
  dplyr::select(team, year, orating, orating_previous, orating_rel_change) %>% 
  mutate_if(is.numeric, round, 1) %>% 
  dplyr::rename(Team = team,
                Season = year,
                `Offensive rating` = orating,
                `Offensive rating (previous season)` = orating_previous,
                `Change in rORTG` = orating_rel_change)

reactable::reactable(
  ratings,
  columns = list(
    `Change in rORTG` = colDef(
      maxWidth = 55,
      class = "cell number",
      cell = function(value){
        scaled <- 1 - (value - min(ratings$`Change in rORTG`)) / (max(ratings$`Change in rORTG`) - min(ratings$`Change in rORTG`))
        color <- ratings_color(scaled)
        div(class = "spi-rating", style = list(background = color), value)
      }
    )
  )
)
```

